In [130]:
import pandas as pd

In [131]:
data = pd.read_csv("gameLogs.csv")

In [132]:
data = data.dropna()

In [133]:
data.describe()

,Unnamed: 0,TEAM_ID,W,L,W_HOME,L_HOME,W_ROAD,L_ROAD,TEAM_TURNOVERS,TEAM_REBOUNDS,...,SCORING_MARGIN,GAME_ID,HOME_FLAG,AWAY_FLAG,HOME_WIN_PCTG,AWAY_WIN_PCTG,TOTAL_WIN_PCTG,ROLLING_SCORING_MARGIN,ROLLING_OE,NUM_REST_DAYS
count,6943.000000,6.943000e+03,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,...,6943.000000,6.943000e+03,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000,6943.000000
mean,3541.274521,1.610613e+09,0.499928,0.500072,0.278266,0.221518,0.221662,0.278554,0.664698,7.898603,...,-0.008066,2.210492e+07,0.499784,0.500216,0.558136,0.444275,0.501230,0.012915,0.564972,2.093331
std,2041.963628,8.660495e+00,0.500036,0.500036,0.448177,0.415298,0.415395,0.448320,0.815739,2.953949,...,14.827859,8.062371e+04,0.500036,0.500036,0.193634,0.190231,0.153682,9.294921,0.033839,0.990994
min,0.000000,1.610613e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-73.000000,2.200000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,-38.000000,0.429059,1.000000
25%,1777.500000,1.610613e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,...,-10.000000,2.200089e+07,0.000000,0.000000,0.437500,0.333333,0.414634,-6.000000,0.542641,2.000000
50%,3541.000000,1.610613e+09,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,...,-1.000000,2.210070e+07,0.000000,1.000000,0.562500,0.437500,0.500000,0.000000,0.565603,2.000000
75%,5308.500000,1.610613e+09,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,10.000000,...,10.000000,2.220036e+07,1.000000,1.000000,0.666667,0.566667,0.602941,6.333333,0.588335,2.000000
max,7079.000000,1.610613e+09,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,23.000000,...,73.000000,2.220123e+07,1.000000,1.000000,1.000000,1.000000,1.000000,35.666667,0.677515,13.000000

In [134]:
data.columns

Index(['Unnamed: 0', 'CITY', 'NICKNAME', 'TEAM_ID', 'W', 'L', 'W_HOME',
       'L_HOME', 'W_ROAD', 'L_ROAD', 'TEAM_TURNOVERS', 'TEAM_REBOUNDS', 'GP',
       'GS', 'ACTUAL_MINUTES', 'ACTUAL_SECONDS', 'FG', 'FGA', 'FG_PCT', 'FG3',
       'FG3A', 'FG3_PCT', 'FT', 'FTA', 'FT_PCT', 'OFF_REB', 'DEF_REB',
       'TOT_REB', 'AST', 'PF', 'STL', 'TOTAL_TURNOVERS', 'BLK', 'PTS',
       'AVG_REB', 'AVG_PTS', 'DQ', 'OFFENSIVE_EFFICIENCY', 'SCORING_MARGIN',
       'SEASON', 'GAME_DATE', 'GAME_ID', 'HOME_FLAG', 'AWAY_FLAG',
       'HOME_WIN_PCTG', 'AWAY_WIN_PCTG', 'TOTAL_WIN_PCTG',
       'ROLLING_SCORING_MARGIN', 'ROLLING_OE', 'NUM_REST_DAYS'],
      dtype='object')

In [135]:
data = data.drop(["Unnamed: 0","NICKNAME","GP","GS","ACTUAL_MINUTES","ACTUAL_SECONDS","FG","FGA","FG3","FG3A","FT","FTA","OFF_REB","DEF_REB","PF","AVG_REB","AVG_PTS","DQ","SCORING_MARGIN","HOME_FLAG","AWAY_FLAG"],axis=1).sort_values("GAME_DATE")
data["LAST_3_GAME_AVG_OE"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['OFFENSIVE_EFFICIENCY'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['OFFENSIVE_EFFICIENCY'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['OFFENSIVE_EFFICIENCY'].shift(3)))/3
data["LAST_3_GAME_AVG_HOME_WIN_PCTG"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['HOME_WIN_PCTG'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['HOME_WIN_PCTG'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['HOME_WIN_PCTG'].shift(3)))/3
data["LAST_3_GAME_AVG_AWAY_WIN_PCTG"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AWAY_WIN_PCTG'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AWAY_WIN_PCTG'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AWAY_WIN_PCTG'].shift(3)))/3
data["LAST_3_GAME_AVG_TOTAL_WIN_PCTG"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_WIN_PCTG'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_WIN_PCTG'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_WIN_PCTG'].shift(3)))/3
data["LAST_3_GAME_AVG_ROLLING_SCORING_MARGIN"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_SCORING_MARGIN'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_SCORING_MARGIN'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_SCORING_MARGIN'].shift(3)))/3
data["LAST_3_GAME_AVG_ROLLING_OE"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(3)))/3
data["LAST_3_GAME_AVG_FG_PCT"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FG_PCT'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FG_PCT'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FG_PCT'].shift(3)))/3
data["LAST_3_GAME_AVG_FG3_PCT"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FG3_PCT'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FG3_PCT'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FG3_PCT'].shift(3)))/3
data["LAST_3_GAME_AVG_FT_PCT"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FT_PCT'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FT_PCT'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['FT_PCT'].shift(3)))/3
data["LAST_3_GAME_ROLLING_OE"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(3)))/3
data["LAST_3_GAME_AVG_TOT_REB"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOT_REB'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOT_REB'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOT_REB'].shift(3)))/3
data["LAST_3_GAME_AVG_AST"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AST'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AST'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AST'].shift(3)))/3
data["LAST_3_GAME_AVG_STL"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['STL'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['STL'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['STL'].shift(3)))/3
data["LAST_3_GAME_AVG_TOTAL_TURNOVERS"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_TURNOVERS'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_TURNOVERS'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_TURNOVERS'].shift(3)))/3
data["LAST_3_GAME_ACG_BLK"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['BLK'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['BLK'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['BLK'].shift(3)))/3
data["LAST_3_GAME_AVG_PTS"] = ((data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['PTS'].shift(1)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['PTS'].shift(2)) + (data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['PTS'].shift(3)))/3
data=data.dropna

In [136]:
def getHomeTeamFrame(gameDF):
        homeTeamFrame = gameDF[gameDF['CITY'] != 'OPPONENTS']
        homeTeamFrame = homeTeamFrame[['LAST_3_GAME_OE','LAST_3_GAME_HOME_WIN_PCTG','NUM_REST_DAYS','LAST_3_GAME_AWAY_WIN_PCTG','LAST_3_GAME_TOTAL_WIN_PCTG','LAST_3_GAME_ROLLING_SCORING_MARGIN','LAST_3_GAME_ROLLING_OE','W','TEAM_ID','GAME_ID','SEASON',"LAST_3_GAME_AVG_FG_PCT","LAST_3_GAME_AVG_FG3_PCT","LAST_3_GAME_AVG_FT_PCT","LAST_3_GAME_ROLLING_OE","LAST_3_GAME_AVG_TOT_REB","LAST_3_GAME_AVG_AST","LAST_3_GAME_AVG_STL","LAST_3_GAME_AVG_TOTAL_TURNOVERS","LAST_3_GAME_ACG_BLK","LAST_3_GAME_AVG_PTS"]]

        colRenameDict = {}
        for col in homeTeamFrame.columns:
            if (col != 'GAME_ID') & (col != 'SEASON') :
                colRenameDict[col] = 'HOME_' + col 

        homeTeamFrame.rename(columns=colRenameDict,inplace=True)

        return homeTeamFrame

In [137]:
def getAwayTeamFrame(gameDF):
        awayTeamFrame = gameDF[gameDF['CITY'] == 'OPPONENTS']
        awayTeamFrame = awayTeamFrame[['LAST_3_GAME_OE','LAST_3_GAME_HOME_WIN_PCTG','NUM_REST_DAYS','LAST_3_GAME_AWAY_WIN_PCTG','LAST_3_GAME_TOTAL_WIN_PCTG','LAST_3_GAME_ROLLING_SCORING_MARGIN','LAST_3_GAME_ROLLING_OE','W','TEAM_ID','GAME_ID','SEASON',"LAST_3_GAME_AVG_FG_PCT","LAST_3_GAME_AVG_FG3_PCT","LAST_3_GAME_AVG_FT_PCT","LAST_3_GAME_ROLLING_OE","LAST_3_GAME_AVG_TOT_REB","LAST_3_GAME_AVG_AST","LAST_3_GAME_AVG_STL","LAST_3_GAME_AVG_TOTAL_TURNOVERS","LAST_3_GAME_ACG_BLK","LAST_3_GAME_AVG_PTS"]]

        colRenameDict = {}
        for col in awayTeamFrame.columns:
            if (col != 'GAME_ID') & (col != 'SEASON'):
                colRenameDict[col] = 'AWAY_' + col 

        awayTeamFrame.rename(columns=colRenameDict,inplace=True)

        return awayTeamFrame

In [138]:
awayTeamFrame = getAwayTeamFrame(data)
homeTeamFrame = getHomeTeamFrame(data)
pd.merge(homeTeamFrame, awayTeamFrame, how="inner", on=[ "GAME_ID","SEASON"]).drop(['GAME_ID','AWAY_TEAM_ID','HOME_TEAM_ID'],axis=1)

TypeError: 'method' object is not subscriptable

In [ ]:
data20 = data[data["SEASON"] == "2020-21"]
data21 = data[data["SEASON"] == "2021-22"]
data22 = data[data["SEASON"] == "2022-23"]

In [ ]:
data21

,CITY,TEAM_ID,W,L,W_HOME,L_HOME,W_ROAD,L_ROAD,TEAM_TURNOVERS,TEAM_REBOUNDS,...,LAST_3_GAME_AVG_FG_PCT,LAST_3_GAME_AVG_FG3_PCT,LAST_3_GAME_AVG_FT_PCT,LAST_3_GAME_ROLLING_OE,LAST_3_GAME_AVG_TOT_REB,LAST_3_GAME_AVG_AST,LAST_3_GAME_AVG_STL,LAST_3_GAME_AVG_TOTAL_TURNOVERS,LAST_3_GAME_ACG_BLK,LAST_3_GAME_AVG_PTS
3318,Los Angeles,1610612747,0,1,0,1,0,0,1,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3860,Milwaukee,1610612749,1,0,1,0,0,0,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3319,OPPONENTS,1610612744,1,0,0,0,1,0,0,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3861,OPPONENTS,1610612751,0,1,0,0,0,1,1,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4186,San Antonio,1610612759,1,0,1,0,0,0,0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3441,OPPONENTS,1610612760,0,1,0,0,0,1,2,6,...,0.449000,0.316333,0.645333,0.555095,47.333333,21.000000,8.666667,13.666667,5.333333,100.000000
2920,Dallas,1610612742,1,0,1,0,0,0,0,8,...,0.536000,0.440000,0.809333,0.583441,52.333333,27.000000,8.000000,13.000000,3.000000,125.666667
2630,New Orleans,1610612740,0,1,0,1,0,0,1,6,...,0.478333,0.343667,0.796667,0.598129,52.000000,26.666667,12.666667,13.666667,2.000000,121.333333
2631,OPPONENTS,1610612744,1,0,0,0,1,0,0,5,...,0.484000,0.407000,0.840333,0.586196,54.000000,30.333333,8.666667,14.666667,4.666667,112.333333
3440,LA,1610612746,1,0,1,0,0,0,0,7,...,0.467333,0.439333,0.798333,0.605230,54.333333,27.333333,8.000000,14.666667,5.666667,116.333333