In [19]:
import pandas as pd

In [20]:
data = pd.read_csv("GettingData/gameLogs.csv")

In [21]:
data.dropna()

,Unnamed: 0,CITY,NICKNAME,TEAM_ID,W,L,W_HOME,L_HOME,W_ROAD,L_ROAD,...,GAME_DATE,GAME_ID,HOME_FLAG,AWAY_FLAG,HOME_WIN_PCTG,AWAY_WIN_PCTG,TOTAL_WIN_PCTG,ROLLING_SCORING_MARGIN,ROLLING_OE,NUM_REST_DAYS
0,0,Atlanta,Hawks,1610612737,1,0,1,0,0,0,...,2021-05-16,22001066,1,0,0.694444,0.444444,0.569444,18.666667,0.594231,3.0
1,1,OPPONENTS,Rockets,1610612745,0,1,0,0,0,1,...,2021-05-16,22001066,0,1,0.250000,0.222222,0.236111,-8.000000,0.559973,2.0
2,2,Atlanta,Hawks,1610612737,1,0,1,0,0,0,...,2021-05-13,22001049,1,0,0.685714,0.444444,0.563380,9.333333,0.571405,1.0
3,3,OPPONENTS,Magic,1610612753,0,1,0,0,0,1,...,2021-05-13,22001049,0,1,0.305556,0.294118,0.300000,-22.333333,0.502823,2.0
4,4,Atlanta,Hawks,1610612737,1,0,1,0,0,0,...,2021-05-12,22001042,1,0,0.676471,0.444444,0.557143,-0.666667,0.589472,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7075,7075,OPPONENTS,Pistons,1610612765,0,1,0,0,0,1,...,2023-02-27,22200919,0,1,0.266667,0.218750,0.241935,-5.666667,0.529425,2.0
7076,7076,Detroit,Pistons,1610612765,1,0,1,0,0,0,...,2023-02-03,22200785,1,0,0.269231,0.259259,0.264151,-1.000000,0.545693,4.0
7077,7077,OPPONENTS,Hornets,1610612766,0,1,0,0,0,1,...,2023-02-03,22200785,0,1,0.304348,0.258065,0.277778,-10.333333,0.524888,1.0
7078,7078,Charlotte,Hornets,1610612766,0,1,0,1,0,0,...,2022-12-14,22200414,1,0,0.285714,0.214286,0.250000,-14.666667,0.530214,3.0
7079,7079,OPPONENTS,Pistons,1610612765,1,0,0,0,1,0,...,2022-12-14,22200414,0,1,0.307692,0.235294,0.266667,-3.666667,0.557132,3.0

In [22]:
data.describe()

,Unnamed: 0,TEAM_ID,W,L,W_HOME,L_HOME,W_ROAD,L_ROAD,TEAM_TURNOVERS,TEAM_REBOUNDS,...,SCORING_MARGIN,GAME_ID,HOME_FLAG,AWAY_FLAG,HOME_WIN_PCTG,AWAY_WIN_PCTG,TOTAL_WIN_PCTG,ROLLING_SCORING_MARGIN,ROLLING_OE,NUM_REST_DAYS
count,7080.000000,7.080000e+03,7080.000000,7080.000000,7080.000000,7080.000000,7080.000000,7080.000000,7080.000000,7080.000000,...,7080.000000,7.080000e+03,7080.000000,7080.000000,7013.000000,7010.000000,7080.000000,7080.000000,7080.000000,6990.000000
mean,3539.500000,1.610613e+09,0.500000,0.500000,0.278249,0.221751,0.221751,0.278249,0.662429,7.918785,...,0.000000,2.210483e+07,0.500000,0.500000,0.557734,0.444047,0.500630,0.004284,0.564587,2.094421
std,2043.964285,8.656053e+00,0.500035,0.500035,0.448168,0.415454,0.415454,0.448168,0.814580,2.959450,...,14.833968,8.070488e+04,0.500035,0.500035,0.197644,0.194585,0.164713,9.390859,0.034162,0.988971
min,0.000000,1.610613e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-73.000000,2.200000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,-38.000000,0.396396,1.000000
25%,1769.750000,1.610613e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,...,-10.000000,2.200089e+07,0.000000,0.000000,0.437500,0.333333,0.411765,-6.333333,0.542231,2.000000
50%,3539.500000,1.610613e+09,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,...,0.000000,2.210069e+07,0.500000,0.500000,0.562500,0.437500,0.500000,0.000000,0.565259,2.000000
75%,5309.250000,1.610613e+09,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,10.000000,...,10.000000,2.220035e+07,1.000000,1.000000,0.675676,0.567568,0.604167,6.333333,0.588179,2.000000
max,7079.000000,1.610613e+09,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,23.000000,...,73.000000,2.220123e+07,1.000000,1.000000,1.000000,1.000000,1.000000,42.000000,0.677515,13.000000

In [23]:
data.columns

Index(['Unnamed: 0', 'CITY', 'NICKNAME', 'TEAM_ID', 'W', 'L', 'W_HOME',
       'L_HOME', 'W_ROAD', 'L_ROAD', 'TEAM_TURNOVERS', 'TEAM_REBOUNDS', 'GP',
       'GS', 'ACTUAL_MINUTES', 'ACTUAL_SECONDS', 'FG', 'FGA', 'FG_PCT', 'FG3',
       'FG3A', 'FG3_PCT', 'FT', 'FTA', 'FT_PCT', 'OFF_REB', 'DEF_REB',
       'TOT_REB', 'AST', 'PF', 'STL', 'TOTAL_TURNOVERS', 'BLK', 'PTS',
       'AVG_REB', 'AVG_PTS', 'DQ', 'OFFENSIVE_EFFICIENCY', 'SCORING_MARGIN',
       'SEASON', 'GAME_DATE', 'GAME_ID', 'HOME_FLAG', 'AWAY_FLAG',
       'HOME_WIN_PCTG', 'AWAY_WIN_PCTG', 'TOTAL_WIN_PCTG',
       'ROLLING_SCORING_MARGIN', 'ROLLING_OE', 'NUM_REST_DAYS'],
      dtype='object')

In [24]:
data['LAST_GAME_OE'] = data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['OFFENSIVE_EFFICIENCY'].shift(1)
data['LAST_GAME_HOME_WIN_PCTG'] = data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['HOME_WIN_PCTG'].shift(1)
data['LAST_GAME_AWAY_WIN_PCTG'] = data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['AWAY_WIN_PCTG'].shift(1)
data['LAST_GAME_TOTAL_WIN_PCTG'] = data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['TOTAL_WIN_PCTG'].shift(1)
data['LAST_GAME_ROLLING_SCORING_MARGIN'] = data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_SCORING_MARGIN'].shift(1)
data['LAST_GAME_ROLLING_OE'] = data.sort_values('GAME_DATE').groupby(['TEAM_ID','SEASON'])['ROLLING_OE'].shift(1)
data

,Unnamed: 0,CITY,NICKNAME,TEAM_ID,W,L,W_HOME,L_HOME,W_ROAD,L_ROAD,...,TOTAL_WIN_PCTG,ROLLING_SCORING_MARGIN,ROLLING_OE,NUM_REST_DAYS,LAST_GAME_OE,LAST_GAME_HOME_WIN_PCTG,LAST_GAME_AWAY_WIN_PCTG,LAST_GAME_TOTAL_WIN_PCTG,LAST_GAME_ROLLING_SCORING_MARGIN,LAST_GAME_ROLLING_OE
0,0,Atlanta,Hawks,1610612737,1,0,1,0,0,0,...,0.569444,18.666667,0.594231,3.0,0.555556,0.685714,0.444444,0.563380,9.333333,0.571405
1,1,OPPONENTS,Rockets,1610612745,0,1,0,0,0,1,...,0.236111,-8.000000,0.559973,2.0,0.612903,0.250000,0.228571,0.239437,-2.000000,0.605315
2,2,Atlanta,Hawks,1610612737,1,0,1,0,0,0,...,0.563380,9.333333,0.571405,1.0,0.573913,0.676471,0.444444,0.557143,-0.666667,0.589472
3,3,OPPONENTS,Magic,1610612753,0,1,0,0,0,1,...,0.300000,-22.333333,0.502823,2.0,0.500000,0.305556,0.303030,0.304348,-18.000000,0.512228
4,4,Atlanta,Hawks,1610612737,1,0,1,0,0,0,...,0.557143,-0.666667,0.589472,2.0,0.584746,0.666667,0.444444,0.550725,8.666667,0.640592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7075,7075,OPPONENTS,Pistons,1610612765,0,1,0,0,0,1,...,0.241935,-5.666667,0.529425,2.0,0.537815,0.266667,0.225806,0.245902,-8.000000,0.538467
7076,7076,Detroit,Pistons,1610612765,1,0,1,0,0,0,...,0.264151,-1.000000,0.545693,4.0,0.529412,0.240000,0.259259,0.250000,-0.333333,0.566698
7077,7077,OPPONENTS,Hornets,1610612766,0,1,0,0,0,1,...,0.277778,-10.333333,0.524888,1.0,0.522523,0.304348,0.266667,0.283019,-6.666667,0.550896
7078,7078,Charlotte,Hornets,1610612766,0,1,0,1,0,0,...,0.250000,-14.666667,0.530214,3.0,0.513043,0.307692,0.214286,0.259259,-14.333333,0.556458
7079,7079,OPPONENTS,Pistons,1610612765,1,0,0,0,1,0,...,0.266667,-3.666667,0.557132,3.0,0.577236,0.307692,0.187500,0.241379,-8.000000,0.512440

In [25]:
def getHomeTeamFrame(gameDF):
        homeTeamFrame = gameDF[gameDF['CITY'] != 'OPPONENTS']
        homeTeamFrame = homeTeamFrame[['LAST_GAME_OE','LAST_GAME_HOME_WIN_PCTG','NUM_REST_DAYS','LAST_GAME_AWAY_WIN_PCTG','LAST_GAME_TOTAL_WIN_PCTG','LAST_GAME_ROLLING_SCORING_MARGIN','LAST_GAME_ROLLING_OE','W','TEAM_ID','GAME_ID','SEASON']]

        colRenameDict = {}
        for col in homeTeamFrame.columns:
            if (col != 'GAME_ID') & (col != 'SEASON') :
                colRenameDict[col] = 'HOME_' + col 

        homeTeamFrame.rename(columns=colRenameDict,inplace=True)

        return homeTeamFrame

In [26]:
def getAwayTeamFrame(gameDF):
        awayTeamFrame = gameDF[gameDF['CITY'] == 'OPPONENTS']
        awayTeamFrame = awayTeamFrame[['LAST_GAME_OE','LAST_GAME_HOME_WIN_PCTG','NUM_REST_DAYS','LAST_GAME_AWAY_WIN_PCTG','LAST_GAME_TOTAL_WIN_PCTG','LAST_GAME_ROLLING_SCORING_MARGIN','LAST_GAME_ROLLING_OE','TEAM_ID','GAME_ID','SEASON']]

        colRenameDict = {}
        for col in awayTeamFrame.columns:
            if (col != 'GAME_ID') & (col != 'SEASON'):
                colRenameDict[col] = 'AWAY_' + col 

        awayTeamFrame.rename(columns=colRenameDict,inplace=True)

        return awayTeamFrame

In [27]:
awayTeamFrame = getAwayTeamFrame(data)
homeTeamFrame = getHomeTeamFrame(data)
data = pd.merge(homeTeamFrame, awayTeamFrame, how="inner", on=[ "GAME_ID","SEASON"]).drop(['GAME_ID','AWAY_TEAM_ID','HOME_TEAM_ID'],axis=1)
data=data.dropna()

In [28]:
data20 = data[data["SEASON"] == "2020-21"]
data21 = data[data["SEASON"] == "2021-22"]
data22 = data[data["SEASON"] == "2022-23"]

In [29]:
data20.to_csv("OG2020seasonDataforModels")
data21.to_csv("OG2021seasonDataforModels")
data22.to_csv("OG2022seasonDataforModels")